src/main/java/module-info.java

Branch is clean in GitHubActions, but still is marked as failed, as ContinousIntegration marks the dependency-reduced-pom.xml as unsupported file format. 
@12219457 
@SilviaMahr 
Test classes are missing in main!
That is the only way to make it work right now. 
I will create two issues which is open to all of us. If your are willing to fix the tests, feel free to assign yourself. 
Issue 1 will be: fix test merges 
Issue 2 will be: fix issues with dependecy-reduced-pom.xml (if this error still occurs after this merge). 
@12219457 I saved our test-class code and will forward it to you! As soon as we fixed our Issue1 we can add them back.

last try to clean the branch

---

pom.xml

removed shade plugin - not neccessary for terminal start!

pom.xml without shade plugin

---

src/main/java/backend/logic/ReimbursementService.java
src/main/java/frontend/controller/AdminDashboardController.java
src/main/java/frontend/controller/ModifyReimbursementController.java
src/main/resources/frontend/views/AdminDashboard.fxml
src/main/resources/frontend/views/ModifyReimbursement.fxml

still missing: testing, debugging

new: ModifyReimbursement

---

src/main/java/frontend/controller/LoginPageController.java
src/main/resources/frontend/views/LoginPage.fxml

enhancement implemented

---

src/main/resources/frontend/views/AdminDashboard_alt.fxml

because of "RückerstattungsButton"

alter AdminDashboard.fxml

---

src/main/java/backend/logic/ReimbursementService.java
src/main/java/frontend/controller/EditReimbursementController.java
src/main/resources/frontend/views/EditReimbursement.fxml

#11 delete submitted invoices

---

src/main/java/backend/model/Reimbursement.java
src/main/java/frontend/controller/ReimbursementHistoryController.java
src/main/resources/frontend/views/ReimbursementHistory.fxml

missing: edit, logging, informing users

#16 delete submitted invoiced

---

src/main/java/backend/model/Reimbursement.java

#208 debug ReimbursementApproval

---

src/main/java/frontend/controller/StatisticsController.java

method loadStatusBarChart needed additional case Flagged

added flagged to load status bar

---

src/main/java/frontend/controller/InvoiceUploadController.java
src/main/resources/frontend/views/InvoiceUpload.fxml
src/main/resources/frontend/views/UserDropDown.fxml

Invoice upload now has a load button until OCR read is done

Load button

---

src/test/java/lunchifyTests/UserServiceTest.java

Methods which call de database for lists of employees are not tested, because testing is not useful

Added test cases for UserService, increased coverage by almost 15 %

---

src/test/java/lunchifyTests/AdminTests.java

Added test cases for class Admin #212

---

src/main/resources/frontend/views/AdminDashboard.fxml

cleaned an rearranged AdminDashboard #224

---

src/main/java/backend/logic/ExportService.java

enhanced csv-export functionality

improved csv-export

---

src/main/java/backend/logic/UserService.java
src/main/java/frontend/controller/NotificationsController.java
src/main/resources/frontend/views/Notification.fxml

enhance notification table #235

---

src/main/java/backend/logic/ExportService.java

fixed PDM errors ExportService

---

src/main/java/backend/model/FlaggedUser.java
src/main/java/frontend/controller/InvoiceUploadController.java

Silvia pmd findings 20250519

---

src/main/java/frontend/controller/UserDropDownController.java
src/main/resources/frontend/views/UserDropDown.fxml

No longer necessary - not needed in this application

removed change password button

---

src/main/java/frontend/controller/CurrReimbursementController.java
src/main/resources/frontend/views/currReimbursements.fxml

fixed no data label in currReimbursements

---

src/main/java/frontend/controller/AdminDashboardController.java
src/main/java/frontend/controller/AnomalyDetectionController.java
src/main/java/frontend/controller/EditReimbursementController.java
src/main/java/frontend/controller/LoginPageController.java

changed window-titles

---

src/main/java/frontend/controller/FlaggedUserController.java

To remove the permanent flag only the users who are permanently flagged need the button

edit button for perm flagged users only

---

src/main/java/backend/logic/OCRService.java
src/main/java/frontend/controller/AnomalyDetectionController.java

Admins now can´t edit, reject, approve or delete their own reimbursements in anomaly detection.

Suspicious invoices not managable by owner in anomaly detection

---

pom.xml
src/main/java/backend/logic/AnomalyDetectionService.java
src/main/java/backend/logic/ExportService.java
src/main/java/backend/logic/FlaggedUserService.java
src/main/java/backend/logic/InvoiceService.java
src/main/java/backend/logic/LocalDateAdapter.java
src/main/java/backend/logic/NotificationService.java
src/main/java/backend/logic/OCRService.java
src/main/java/backend/logic/SearchService.java
src/main/java/backend/logic/SessionManager.java
src/main/java/backend/logic/StatisticsService.java
src/main/java/backend/logic/UserService.java

All PMD errors are fixed now
JavaDoc comments for ServiceClasses (except ReimbursementService)

Release prep
